api/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # Stable
    url(r'', include('api.v1.urls')),
    # Version
    url(r'^v1/', include('api.v1.urls')),
]

api/v1/service/urls.py
from django.conf.urls import url

from .views import (
    ServiceListView,
    ServiceFilterListView,
    ServiceCreateView,
    CategoryListView,
    CategoryDetailView
)

urlpatterns = [
    url(r'^(?P<enterprise_id>[\w-]+)/$', ServiceListView.as_view(), name='service-list'),
    url(r'^filter/(?P<category_id>[\w-]+)/$', ServiceFilterListView.as_view(), name='service-filter'),
    url(r'^create/(?P<company_id>[\w-]+)/(?P<service_id>[\w-]+)/$', ServiceCreateView.as_view(), name='service-create'),
    url(r'^category/(?P<company_id>[\w-]+)/$', CategoryListView.as_view(), name='category-list'),
    url(r'^category/detail/(?P<pk>[\w-]+)/$', CategoryDetailView.as_view(), name='category-detail'),
]

enterprise/urls.py
from django.conf.urls import url

from .views import (
    dashboard,
    create,
    detail,
    update
)

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    # OLD
    url(r'^enterprise/create/(?P<pk>[\w-]+)/$', create, name='create'),
    url(r'^enterprise/detail/(?P<pk>[\w-]+)/$', detail, name="detail"),
    url(r'^enterprise/update/(?P<pk>[\w-]+)/$', update, name="update"),
]

reservator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = i18n_patterns(
    # apps urls
    # flatpages
    url(r'^$', include('django.contrib.flatpages.urls')),
    # admin dashboard
    url(r'^dashboard/', include('enterprise.urls', namespace='enterprise')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^service/', include('service.urls', namespace='service')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    # auth
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Social
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^api/enterprise/', include('enterprise.api.urls', namespace='api-enterprise')),
    # url(r'^api/employee/', include('employee.api.urls', namespace='api-employee')),
    # url(r'^api/profile/', include('account.api.profile.urls', namespace='api-profile')),
    # url(r'^api/auth/', include('account.api.urls', namespace='api-auth')),
    # Languages
    url(r'^lang/(?P<lang_code>[a-z]{2})/$', views.lang, name='lang'),
    # Ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # admin
    url(r'^area51/', admin.site.urls),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

service/urls.py
from django.conf.urls import url

from .views import (
    service,
    service_detail,
    service_update,
    category_detail
)

urlpatterns = [
    url(r'^$', service, name='service'),
    url(r'^detail/(?P<service_id>[\w-]+)$', service_detail, name='service-detail'),
    url(r'^update/(?P<service_id>[\w-]+)$', service_update, name='service-update'),
    url(r'^category/detail/(?P<category_id>[\w-]+)$', category_detail, name='category-detail'),
]

settings/urls.py
from django.conf.urls import url

from .views import (
    enterprise_update,
    update_logo,
    personal,
    add_employee,
    personal_detail,
    new_category,
    service,
    new_service
)

urlpatterns = [
    url(r'^change/update/(?P<pk>[\w-]+)/$', enterprise_update, name='enterprise-settings'),
    url(r'^change/logo/(?P<pk>[\w-]+)/$', update_logo, name='enterprise-logo'),
    url(r'^change/personal/(?P<pk>[\w-]+)/$', personal, name='personal-settings'),
    url(r'^service/create-serivce', new_service, name='new-service'),
    url(r'^personal/add', add_employee, name='add-personal'),
    url(r'^personal/update(?P<pk>[\w-]+)/$', personal_detail, name='staff-detail'),
    url(r'^group/company-(?P<pk>[\w-]+)/$', service, name='service-group'),
    url(r'^group/new/(?P<pk>[\w-]+)/$', new_category, name='new-category'),
]

service/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import gettext_lazy as _

from enterprise.models import Enterprise


# Create your models here.
price = (
    ('UAH', 'UAH'),
    ('RUB', 'RUB')
)


class Category(models.Model):
    enterprise = models.ForeignKey(Enterprise, help_text='Select enterprise', related_name='services')
    title = models.CharField(max_length=255, help_text='Name category of services')
    weight = models.PositiveIntegerField(default=1, help_text='Priority')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'db_category'
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("service:category-detail", kwargs={'category_id': self.pk})


class Service(models.Model):
    enterprise = models.ForeignKey(Enterprise, related_name='Owner')
    title = models.CharField(max_length=255, help_text='Name of service')
    service_desc = models.TextField(help_text='Short description', blank=True, null=True)
    service_duration = models.DurationField(blank=True, null=True, verbose_name=_('Service duration'))
    price = models.CharField(max_length=50, choices=price, help_text='Select currency', default='UAH')
    min_price = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name=_('Min price'))
    max_price = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name=_('Max price'))
    service = models.ForeignKey(Category, help_text='Select category', related_name='service')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    access = models.BooleanField(default=False)

    class Meta:
        db_table = 'db_service'
        verbose_name = _('Service')
        verbose_name_plural = _('Services')
        ordering = ['-title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('service:service-detail', kwargs={'service_id': self.pk})

    def get_update_url(self):
        return reverse('service:service-update', kwargs={'service_id': self.pk})

service/forms.py
from django import forms
from .models import Category, Service


class CategoryCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Название категории')
    weight = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '0'
    }), label='Приоритет')

    class Meta:
        model = Category
        fields = ('title', 'weight',)


class ServiceCreateForm(forms.ModelForm):
        
    def __init__(self, enterprise, *args, **kwargs):
        super(ServiceCreateForm, self).__init__(*args, **kwargs)
        self.fields['service'].queryset = Category.objects.filter(enterprise=enterprise)
    
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Услуга')
    service_desc = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control'}), label='Короткое описание')
    service_duration = forms.DurationField(widget=forms.TimeInput(attrs={'class': 'timepicker'}))
    min_price = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ), label='Минимальная цена')
    max_price = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control'}
    ), label='Максимальная цена')
    access = forms.BooleanField(widget=forms.CheckboxInput, label='Доступен для записи')

    class Meta:
        model = Service
        fields = ('title', 'service_desc', 'service_duration', 'min_price', 'max_price', 'access', 'service')

api/v1/service/views.py
from rest_framework import generics, permissions, mixins
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse
from rest_framework.response import Response

from .serializer import CategorySerializer, CategoryDetailSerialize, ServiceSerializer
from service.models import Category, Service


class CategoryListView(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = CategorySerializer

    def get_queryset(self):
        company_id = self.kwargs['company_id']
        return Category.objects.filter(enterprise=company_id)


class CategoryDetailView(generics.RetrieveAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = CategoryDetailSerialize
    queryset = Category


class ServiceListView(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = ServiceSerializer

    def get_queryset(self):
        enterprise_id = self.kwargs['enterprise_id']
        return Service.objects.filter(enterprise=enterprise_id)


class ServiceFilterListView(generics.ListAPIView):
    serializer_class = ServiceSerializer

    def get_queryset(self):
        category_id = self.kwargs['category_id']
        return Service.objects.filter(service=category_id)


class ServiceCreateView(generics.CreateAPIView, mixins.CreateModelMixin):
    serializer_class = ServiceSerializer

    def get_queryset(self):
        return Service.objects.filter()

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user, servise=self.request.get['service_id'])


class ServiceUpdateView(generics.UpdateAPIView):
    serializer_class = ServiceSerializer


class ServiceDeleteView(generics.DestroyAPIView):
    pass

service/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse

from enterprise.models import Enterprise
from .models import Category, Service
from .forms import ServiceCreateForm


# Create your views here.

@login_required
def service(request):
    categories = Category.objects.filter(enterprise__owner=request.user)
    services = Service.objects.all()
    template_name = 'service/list.html'
    template_data = {'categories': categories, 'services': services}
    return render(request, template_name, template_data)


@login_required
def category_detail(request, category_id):
    category = Category.objects.get(pk=category_id)
    categories = Category.objects.filter(enterprise__owner=request.user).exclude(pk=category.pk)
    services = Service.objects.filter(service=category)
    template_name = 'service/category_detail.html'
    template_data = {'category': category, 'categories': categories, 'services': services}
    return render(request, template_name, template_data)


@login_required
def service_detail(request, service_id):
    services = Service.objects.get(pk=service_id)
    template_name = 'service/service_detail.html'
    template_data = {'services': services}
    return render(request, template_name, template_data)


@login_required
def service_update(request, service_id):
    enterprise = Enterprise.objects.get(owner=request.user)
    instance = Service.objects.get(pk=service_id)
    if request.POST:
        form = ServiceCreateForm(enterprise, request.POST or None, instance=instance)
        if form.is_valid():
            update_data = form.cleaned_data
            Service.objects.filter(pk=service_id).update(**update_data)
            return HttpResponseRedirect(reverse('service:service'))
    else:
        form = ServiceCreateForm(enterprise, instance=instance)
    template_name = 'service/service_update.html'
    template_data = {'service': instance, 'form': form}
    return render(request, template_name, template_data)


def create_category_ajax(request):
    return JsonResponse('Success!')

service/templates/service/category_detail.html
{% extends 'base_index.html' %}

{% block title %}
	{{ category.title }} | {{ block.super }}
{% endblock %}

{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>{{ category.title }}</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'enterprise:dashboard' %}">Главная</a>
            </li>
            <li class="active">
                <strong>Детально</strong>
            </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="col-lg-3">
                <div class="ibox">
                    <div class="ibox-title">
                        <h3>Действия</h3>
                    </div>
                    <div class="ibox-content">
                        <a href="" class="btn btn-success btn-block">Add category</a>
                    </div>
                    <div class="ibox">
                        <div class="ibox-content">
                            <ul class="list-group">
                                <a class="list-group-item">
                                    <i class="fa fa-2x fa-folder-open"></i>
                                    {{ category.title }}    
                                </a>
                                {% for category_list in categories %}
                                <a href="{{ category_list.get_absolute_url }}" class="list-group-item">
                                    <i class="fa fa-2x fa-folder"></i>
                                    {{ category_list.title }}
                                </a>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="col-lg-9">
                <div class="ibox">
                    <div class="ibox-content">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Access</th>
                                    <th>Min price</th>
                                    <th>Max price</th>
                                    <th><a href="{% url 'settings:new-service' %}" class="btn btn-default">New service</a> </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for service in services %}
                                    <tr>
                                        <th><i class="fa fa-bars fa-2x"></i></th>
                                        <td>{{ service.title }}</td>
                                        <td>{{ service.access }}</td>
                                        <td>{{ service.min_price }}</td>
                                        <td>{{ service.max_price }}</td>
                                        <td><a href="{{ service.get_update_url }}" class="btn btn-default btn-xl"><i class="fa fa-cog"></i></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

service/templates/service/list.html
{% extends 'base_index.html' %}
{% load i18n %}
{% block title %}
    Service | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>Project list</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'enterprise:dashboard' %}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>Project list</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInUp">

                <div class="ibox">
                    <div class="ibox-title">
                        <h5>All projects assigned to this account</h5>
                        <div class="ibox-tools">
                            <a href="{% url 'settings:new-category' enterprise.pk %}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> {% trans 'Add category' %}</a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row m-b-sm m-t-sm">
                            <div class="col-md-1">
                                <button type="button" id="loading-example-btn" class="btn btn-white btn-sm"><i
                                        class="fa fa-refresh"></i> Refresh
                                </button>
                            </div>
                            <div class="col-md-11">
                                <div class="input-group"><input type="text" placeholder="Search" class="input-sm form-control">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="project-list">

                            <table class="table table-hover">
                                <tbody>
                                {% for item in categories %}
                                <tr>
                                    <td class="project-status">
                                        <span class="label label-primary">Active</span>
                                    </td>
                                    <td class="project-title">
                                        <a href="{% url 'service:category-detail' item.id %}">{{ item.title }}</a>
                                        <br/>
                                        <small>Created {{ item.created_at }}</small>
                                    </td>
                                    <td class="project-people">
                                        {% for emp in item.get_employee %}
                                        <a href="#"><img alt="{{ emp.name }}" class="img-circle" src="{{ emp.avatar.url }}"></a>
                                        {% endfor %}
                                    </td>
                                    <td class="project-actions">
                                        <a href="{{ item.get_absolute_url }}" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                        <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Edit </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

service/templates/service/service_create.html
{% extends 'base_index.html' %}
{% load i18n %}
{% block title %}
    Create service | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>Услуга</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'enterprise:dashboard' %}">Главная</a>
                </li>
                <li class="active">
                    <strong>Добавить услугу</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInUp">
        <div class="row">
            <div class="col-lg-12">
                <form action="" method="POST" class="form-horizontal wizard-big">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="" class="control-label col-sm-2">
                            {{ field.label_tag }}
                        </label>
                        <div class="col-sm-10">
                            {{ field }}
                            {% if field.errors %}
                                <div class="alert alert-danger">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success btn-sx pull-right">Добавить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function() {
            $('.dual_select').bootstrapDualListbox({
                selectorMinimalHeight: 160
            });
        })
    </script>
{% endblock %}

service/templates/service/service_detail.html
{% extends 'base_index.html' %}

{% block content %}

{% endblock %}

service/templates/service/service_update.html
{% extends 'base_index.html' %}

{% block title %}
	Update {{ service.name }} | {{ block.super }}
{% endblock %}

{% block content %}
		<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактировать</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'enterprise:dashboard' %}">Главная</a>
                </li>
                <li>
                    <a href="">Компания</a>
                </li>
                <li class="active">
                    <strong>Редактировать</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">

        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1"> Основное</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
									<form class="form-horizontal" method="POST" action="">
										{% csrf_token %}
										{% for field in form %}
											<div class="form-group">
												<label class="col-sm-2 control-label" for="">
													{{ field.label_tag }}
												</label>
												<div class="col-sm-10">
													{{ field }}
												</div>
											</div>
										{% endfor %}
										<div class="form-group">
											<div class="col-sm-2 col-sm-offset-2">
												<button class="btn btn-success btn-block">Сохранить!</button>
											</div>
										</div>
									</form>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function() {
            $('.dual_select').bootstrapDualListbox({
                selectorMinimalHeight: 160
            });
        })
    </script>
{% endblock %}