api/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # Stable
    url(r'', include('api.v1.urls')),
    # Version
    url(r'^v1/', include('api.v1.urls')),
]

employee/urls.py
from django.conf.urls import url

from .views import (
    employee,
    new_employee
)

urlpatterns = [
    url(r'^$', employee, name='employee'),
    url(r'^new$', new_employee, name='new-employee'),
]

reservator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = i18n_patterns(
    # apps urls
    # flatpages
    url(r'^$', include('django.contrib.flatpages.urls')),
    # admin dashboard
    url(r'^dashboard/', include('enterprise.urls', namespace='enterprise')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^service/', include('service.urls', namespace='service')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    # auth
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Social
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^api/enterprise/', include('enterprise.api.urls', namespace='api-enterprise')),
    # url(r'^api/employee/', include('employee.api.urls', namespace='api-employee')),
    # url(r'^api/profile/', include('account.api.profile.urls', namespace='api-profile')),
    # url(r'^api/auth/', include('account.api.urls', namespace='api-auth')),
    # Languages
    url(r'^lang/(?P<lang_code>[a-z]{2})/$', views.lang, name='lang'),
    # Ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # admin
    url(r'^area51/', admin.site.urls),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

schedule/urls.py
from django.conf.urls import url

from .views import schedule, staff_schedule

urlpatterns = [
    url(r'^timetable/$', schedule, name='schedule'),
    url(r'^timetable/(?P<staff_pk>[\w-]+)$', staff_schedule, name='staff-schedule'),
]

settings/urls.py
from django.conf.urls import url

from .views import (
    enterprise_update,
    update_logo,
    personal,
    add_employee,
    personal_detail,
    new_category,
    service,
    new_service
)

urlpatterns = [
    url(r'^change/update/(?P<pk>[\w-]+)/$', enterprise_update, name='enterprise-settings'),
    url(r'^change/logo/(?P<pk>[\w-]+)/$', update_logo, name='enterprise-logo'),
    url(r'^change/personal/(?P<pk>[\w-]+)/$', personal, name='personal-settings'),
    url(r'^service/create-serivce', new_service, name='new-service'),
    url(r'^personal/add', add_employee, name='add-personal'),
    url(r'^personal/update(?P<pk>[\w-]+)/$', personal_detail, name='staff-detail'),
    url(r'^group/company-(?P<pk>[\w-]+)/$', service, name='service-group'),
    url(r'^group/new/(?P<pk>[\w-]+)/$', new_category, name='new-category'),
]

settings/views.py
from django.forms import model_to_dict
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from reservator.decorators import manager_required

from event.models import Event
from enterprise.models import Enterprise
from enterprise.forms import (
    EnterpriseCreateForm,
    EnterpriseUpdateForm,
    EnterpriseUpdateLogoForm,
    EnterpriseUpdateContactForm,
    EnterpriseUpdateScheduleForm
)

from employee.models import Employee
from employee.forms import EmployeeForm

from service.models import Category, Service
from service.forms import CategoryCreateForm, ServiceCreateForm


# Write you views here

@manager_required
def enterprise_update(request, pk):
    instance = Enterprise.objects.get(pk=pk)
    logo_form = EnterpriseUpdateLogoForm(initial=model_to_dict(instance))
    if request.POST:
        form = EnterpriseCreateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            update_data = form.cleaned_data
            Enterprise.objects.filter(owner=request.user).update(**update_data)
            return HttpResponseRedirect('/')
    else:
        form = EnterpriseCreateForm(instance=instance)
    template_name = 'settings/enterprise/enterprise_update.html'
    template_data = {
        'instance': instance,
        'form': form,
        'logo_form': logo_form,
    }
    return render(request, template_name, template_data)


@require_POST
def update_logo(request, pk):
    form = EnterpriseUpdateLogoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        update_data = form.cleaned_data
        print('Form data \n', update_data)
        Enterprise.objects.filter(pk=pk).update(**update_data)
        return HttpResponseRedirect('/')


@manager_required
def personal(request, pk):
    enterprise = Enterprise.objects.get(pk=pk)
    employee = Employee.objects.filter(enterprise=enterprise)
    if request.POST:
        form = EmployeeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form_data = form.cleaned_data
            new_staff = Employee.objects.create(enterprise=enterprise, **form_data)
            new_staff.save()
            return HttpResponseRedirect('/')
    else:
        form = EmployeeForm(request.POST or None)
    template_name = 'settings/staff/personal.html'
    template_data = {'employee': employee, 'form': form}
    return render(request, template_name, template_data)


@manager_required
def add_employee(request):
    if request.POST:
        form = EmployeeForm(request.POST or None, request.FILES or None)
    else:
        form = EmployeeForm()
    template_data = {'form': form}
    template_name = 'settings/staff/new-staff.html'
    return render(request, template_name, template_data)


@manager_required
def personal_detail(request, pk):
    instance = Employee.objects.get(pk=pk)
    events = Event.objects.filter(staff=instance)
    template_name = 'settings/staff/staff-detail.html'
    template_data = {'instance': instance, 'events': events}
    return render(request, template_name, template_data)


@manager_required
def service(request, pk):
    user = request.user
    category = Category.objects.filter(enterprise__owner=user)
    services = Service.objects.filter(service=category)
    template_name = 'settings/service/service_group.html'
    template_data = {'category': category, 'service': services}
    return render(request, template_name, template_data)


@manager_required
def new_category(request, pk):
    user = request.user
    instance = Enterprise.objects.get(pk=pk)
    if request.POST:
        form = CategoryCreateForm(request.POST or None)
        if form.is_valid():
            post_data = form.cleaned_data
            Category.objects.get_or_create(enterprise=instance, **post_data)
            return HttpResponseRedirect(reverse('settings:service-group', kwargs={'pk': instance.pk}))
    else:
        form = CategoryCreateForm()
    template_name = 'settings/service/new_category.html'
    template_data = {'form': form}
    return render(request, template_name, template_data)


@manager_required
def new_service(request):
    enterprise = Enterprise.objects.get(owner=request.user)
    if request.POST:
        form = ServiceCreateForm(enterprise, request.POST or None)
        if form.is_valid():
            post_data = form.cleaned_data
            Service.objects.create(enterprise=enterprise, **post_data)
            return HttpResponseRedirect(reverse("settings:service-group", kwargs={'pk': enterprise.pk}))
    else:
        form = ServiceCreateForm(enterprise)
    template_name = 'settings/service/new_service.html'
    template_data = {'form': form}
    return render(request, template_name, template_data)

settings/templates/settings/staff/new-staff.html
{% extends 'base_index.html' %}
{% load static i18n %}

{% block title %}
   {% trans 'Add employee' %} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактировать</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">Главная</a>
                </li>
                <li>
                    <a href="{% url 'settings:enterprise-settings' enterprise.pk %}">Настройка</a>
                </li>
                <li class="active">
                    <strong>Сотрудники</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="row">
            <div class="col-lg-12">
                <form action="" class="form-horizontal">
                    {{ form }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

settings/templates/settings/staff/personal.html
{% extends "base_index.html" %}
{% load static i18n %}
{% block title %}
    Personal {{ instance.title }} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактировать</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">Главная</a>
                </li>
                <li>
                    <a href="{% url 'settings:enterprise-settings' enterprise.pk %}">Настройка</a>
                </li>
                <li class="active">
                    <strong>Сотрудники</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-content">
                        <table class="footable table table-stripped toggle-arrow-tiny tablet breakpoint footable-loaded">
                            <thead>
                                <tr>
                                    <th class="footable-visible footable-sortable">

                                    </th>
                                    <th class="footable-visible footable-sortable">
                                        {% trans 'Name' %}
                                        <span class="footable-sort-indicator"></span>
                                    </th>
                                    <th class="footable-visible footable-sortable">
                                        {% trans 'Number of services' %}
                                        <span class="footable-sort-indicator"></span>
                                    </th>
                                    <th class="footable-visible footable-sortable">
                                        {% trans 'Status' %}
                                        <span class="footable-sort-indicator"></span>
                                    </th>
                                    <th class="footable-visible footable-sortable">
                                        <a id='new-staff' class="btn btn-success pull-right" href="{% url 'employee:new-employee' %}"> <i class="fa fa-plus"></i> {% trans 'Add employee' %}</a>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for staff in employee %}
                                    <tr class="footable-even">
                                        <td class="footable-visible footable-first-column">
                                            {% if staff.avatar %}
                                                <img class="img-sm img-circle" src="{{ staff.avatar.url }}" alt="{{ staff.name }}">
                                            {% else %}
                                                <img class="img-sm img-circle" src="{% static 'image/avatar/avatar_man.png' %}" alt="{{ staff.name }}">
                                            {% endif %}
                                        </td>
                                        <td class="footable-visible">

                                            <strong>{{ staff.name }}</strong><br>
                                            <small>{{ staff.specialization }}</small>
                                        </td>
                                        <td class="footable-visible">
                                            <span class="text-center">{{ staff.staff.count }}</span>
                                        </td>
                                        <td class="footable-visible">
                                            {% if staff.fired %}
                                                <span class="label label-danger">Уволен</span>
                                            {% else %}
                                                {% if staff.hidden %}
                                                    <span class="label label-warning">Скрыт</span>
                                                {% else %}
                                                    <span class="label label-primary">Доступен</span>
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                        <td class="text-right footable-visible footable-last-column">
                                            <div class="btn-group">
                                                <a class="btn btn-default btn-xl" href=""><i class="fa fa-cog"></i></a>
                                                <a class="btn btn-default btn-xl" href="{% url 'schedule:schedule' %}"><i class="fa fa-clock-o"></i></a>
                                                <a class="btn btn-default btn-xl" href=""><i class="fa fa-trash"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>

                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script src="{% static 'js/utils/cookie_safe.js' %}"></script>
    <script>
        $(document).ready(function () {
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

        });
    </script>
{% endblock %}

settings/templates/settings/staff/staff-detail.html
{% extends 'base_index.html' %}
{% load static %}
{% block title %}
	{{ instance.name }} | {{ block.super }}
{% endblock  %}

{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Профиль {{ instance.name }}</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index-2.html">Главная</a>
            </li>
            <li>
                <a>Сотрудник</a>
            </li>
            <li class="active">
                <strong>Профиль</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">


    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">

            <div class="profile-image">
            	{% if instance.avatar %}
                	<img src="{{instance.avatar.url}}" class="img-circle circle-border m-b-md" alt="{{instance.name}}">
                {% else %}
                	<img src="{% static 'image/avatar/avatar_man.png' %}" class="img-circle circle-border m-b-md" alt="{{instance.name}}">
                {% endif %}
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h2 class="no-margins">
                            <a href="{% url 'schedule:staff-schedule' instance.id %}">{{ instance.name }}</a>
                        </h2>
                        <h4>{{ instance.specialization }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <table class="table small m-b-xs">
                <tbody>
                <tr>
                    <td>
                        <strong>142</strong> Предоставлено услуг
                    </td>
                    <td>
                        <strong>22</strong> Записи
                    </td>

                </tr>
                <tr>
                    <td>
                        <strong>61</strong> Коментариев
                    </td>
                    <td>
                        <strong>54</strong> Articles
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>154</strong> Tags
                    </td>
                    <td>
                        <strong>32</strong> Friends
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <small>Rating</small>
            <div class="rating"></div>
        </div>


    </div>
    <div class="row">

        <div class="col-lg-3">

            <div class="ibox">
                <div class="ibox-content">
                        <h3>About {{instance.name}}</h3>

                    <p class="small">
                        {{ instance.information|safe }}
                    </p>

                    <p class="small font-bold">
                    	{% if instance.fired %}
                    	<span><i class="fa fa-circle text-navy"></i> Fired</span>
                    	{% else %}
                        <span><i class="fa fa-circle text-navy"></i> Online status</span>
                    	{% endif %}
                    </p>

                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Last clients</h3>
                    <p class="small">
                        If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing
                    </p>
                    <div class="user-friends">
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                        <a href="#"><img alt="image" class="img-circle" src="{% static 'image/avatar/avatar_man.png' %}"></a>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-5">
            <div class="social-feed-box">
                <div class="pull-right social-action dropdown">
                    <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu m-t-xs">
                        <li><a href="#">Config</a></li>
                    </ul>
                </div>
                <div class="social-avatar">
                    <a href="#" class="pull-left">
                        <img alt="image" src="{% static 'image/avatar/avatar_man.png' %}">
                    </a>
                    <div class="media-body">
                        <a href="#">
                            Andrew Williams
                        </a>
                        <small class="text-muted">Today 4:21 pm - 12.06.2014</small>
                    </div>
                </div>
                <div class="social-body">
                    <p>
                        Many desktop publishing packages and web page editors now use Lorem Ipsum as their
                        default model text, and a search for 'lorem ipsum' will uncover many web sites still
                        in their infancy. Packages and web page editors now use Lorem Ipsum as their
                        default model text.
                    </p>

                    <div class="btn-group">
                        <button class="btn btn-white btn-xs"><i class="fa fa-thumbs-up"></i> Like this!</button>
                        <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>
                        <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button>
                    </div>
                </div>
                

            </div>

            <div class="social-feed-box">

                <div class="pull-right social-action dropdown">
                    <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu m-t-xs">
                        <li><a href="#">Config</a></li>
                    </ul>
                </div>
                <div class="social-avatar">
                    <a href="#" class="pull-left">
                        <img alt="image" src="{% static 'image/avatar/avatar_man.png' %}">
                    </a>
                    <div class="media-body">
                        <a href="#">
                            Andrew Williams
                        </a>
                        <small class="text-muted">Today 4:21 pm - 12.06.2014</small>
                    </div>
                </div>
                <div class="social-body">
                    <p>
                        Many desktop publishing packages and web page editors now use Lorem Ipsum as their
                        default model text, and a search for 'lorem ipsum' will uncover many web sites still
                        in their infancy. Packages and web page editors now use Lorem Ipsum as their
                        default model text.
                    </p>
                    <p>
                        Lorem Ipsum as their
                        default model text, and a search for 'lorem ipsum' will uncover many web sites still
                        in their infancy. Packages and web page editors now use Lorem Ipsum as their
                        default model text.
                    </p>
                    <img src="{% static 'image/avatar/avatar_man.png' %}" class="img-responsive">
                    <div class="btn-group">
                        <button class="btn btn-white btn-xs"><i class="fa fa-thumbs-up"></i> Like this!</button>
                        <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>
                        <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-lg-4 m-b-lg">
            <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                {% for event in events %}
                <div class="vertical-timeline-block">
                    <div class="vertical-timeline-icon navy-bg">
                        <i class="fa fa-briefcase"></i>
                    </div>

                    <div class="vertical-timeline-content">
                        <h2>{{ event.service }}</h2>
                        {% if event.comments %}
                            <p>
                                {{ event.comments }}
                            </p>
                        {% endif %}
                        <a href="#" class="btn btn-sm btn-primary"> More info</a>
                            <span class="vertical-date">
                                <small>{{ event.start_event }}</small>
                            </span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_script %}
<script>
	option = {
		max_value: 6,
		step_size: 0.5
	};
	$('.rating').rate(option);
</script>
{% endblock %}