api/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # Stable
    url(r'', include('api.v1.urls')),
    # Version
    url(r'^v1/', include('api.v1.urls')),
]

employee/urls.py
from django.conf.urls import url

from .views import (
    employee,
    new_employee
)

urlpatterns = [
    url(r'^$', employee, name='employee'),
    url(r'^new$', new_employee, name='new-employee'),
]

reservator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = i18n_patterns(
    # apps urls
    # flatpages
    url(r'^$', include('django.contrib.flatpages.urls')),
    # admin dashboard
    url(r'^dashboard/', include('enterprise.urls', namespace='enterprise')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^service/', include('service.urls', namespace='service')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    # auth
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Social
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^api/enterprise/', include('enterprise.api.urls', namespace='api-enterprise')),
    # url(r'^api/employee/', include('employee.api.urls', namespace='api-employee')),
    # url(r'^api/profile/', include('account.api.profile.urls', namespace='api-profile')),
    # url(r'^api/auth/', include('account.api.urls', namespace='api-auth')),
    # Languages
    url(r'^lang/(?P<lang_code>[a-z]{2})/$', views.lang, name='lang'),
    # Ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # admin
    url(r'^area51/', admin.site.urls),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

schedule/urls.py
from django.conf.urls import url

from .views import schedule, staff_schedule

urlpatterns = [
    url(r'^timetable/$', schedule, name='schedule'),
    url(r'^timetable/(?P<staff_pk>[\w-]+)$', staff_schedule, name='staff-schedule'),
]

service/urls.py
from django.conf.urls import url

from .views import (
    service,
    service_detail,
    service_update,
    category_detail
)

urlpatterns = [
    url(r'^$', service, name='service'),
    url(r'^detail/(?P<service_id>[\w-]+)$', service_detail, name='service-detail'),
    url(r'^update/(?P<service_id>[\w-]+)$', service_update, name='service-update'),
    url(r'^category/detail/(?P<category_id>[\w-]+)$', category_detail, name='category-detail'),
]

settings/urls.py
from django.conf.urls import url

from .views import (
    enterprise_update,
    update_logo,
    personal,
    add_employee,
    personal_detail,
    new_category,
    service,
    new_service
)

urlpatterns = [
    url(r'^change/update/(?P<pk>[\w-]+)/$', enterprise_update, name='enterprise-settings'),
    url(r'^change/logo/(?P<pk>[\w-]+)/$', update_logo, name='enterprise-logo'),
    url(r'^change/personal/(?P<pk>[\w-]+)/$', personal, name='personal-settings'),
    url(r'^service/create-serivce', new_service, name='new-service'),
    url(r'^personal/add', add_employee, name='add-personal'),
    url(r'^personal/update(?P<pk>[\w-]+)/$', personal_detail, name='staff-detail'),
    url(r'^group/company-(?P<pk>[\w-]+)/$', service, name='service-group'),
    url(r'^group/new/(?P<pk>[\w-]+)/$', new_category, name='new-category'),
]

templates/snippets/header.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom"
                  action="">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search"
                           id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">

            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'account_login' %}">
                        <i class="fa fa-sign-in"></i> Login
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_signup' %}">
                        <i class="fa fa-sign-up"></i> SignUp
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/snippets/navbar.html
{% load static i18n %}
{% url 'enterprise:dashboard' as dashboard %}
{% url 'enterprise:detail' enterprise.pk as enterprise_detail %}
{% url 'service:service' as service %}
{% url 'employee:employee' as employee %}
<!-- Navigation-->

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            {% if enterprise %}
            <li>
                <div id="side-calendar"></div>
            </li>
            <li class="{% if request.path == dashboard %}active{% endif %}">
                <a href="{{ dashboard }}"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
            </li>
            <li class="{% if request.path == service or request.path == employee or request.path == enterprise %}active{% endif %}">
                <a href="#"><i class="fa fa-pencil"></i>
                    <span class="nav-label">{% trans 'Managers' %}</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    <li class="{% if request.path == service %} active {% endif %}">
                        <a href="{{ service }}">{% trans 'Services' %}</a>
                    </li>
                    <li class="{% if request.path == employee %} active {% endif %}">
                        <a href="{{ employee }}">{% trans 'Employee' %}</a>
                    </li>
                    <li><a href="">Clients</a></li>
                    <li class="{% if request.path == enterprise %} active {% endif %}">
                        <a href="{{ enterprise_detail }}"> {% trans 'Enterprise' %}</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="">
                    <i class="fa fa-user-circle"></i>
                    <span class="nav-label">{% trans 'Employee' %}</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    {% for staff in enterprise.get_employee %}
                        <li>
                            <a href="{% url 'settings:staff-detail' staff.pk %}">
                                {% if staff.avatar %}
                                    <img src="{{ staff.avatar.url }}" width="20px" class="img-circle pull-left" alt="">
                                    <span> {{ staff.name }}</span>
                                {% else %}
                                    <img src="{% static 'image/avatar/avatar_man.png' %}" width="20px" class="img-circle pull-left" alt="{{ staff.name }}">
                                    <span> {{ staff.name }}</span>
                                {% endif %}
                                <span class="fa fa-calendar pull-right"></span>
                            </a>
                        </li>
                    {% empty %}
                        <li>
                            <a href="{% url 'settings:personal-settings' enterprise.id %}">Добавить сотрудников</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li>
                <a href="{% url 'schedule:schedule' %}"><i class="fa fa-calendar"></i> <span class="nav-label"> Росписание</span></a>
            </li>
            <li>
                <a id="settings-toggle" href="">
                    <i class="fa fa-cogs"></i>
                    <span class="nav-label">Настройка</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{% url 'settings:enterprise-settings' enterprise.pk %}"><span class="fa fa-edit"></span> Основное</a></li>
                    <li><a href="{% url 'settings:service-group' enterprise.pk %}"><span class="fa fa-tasks"></span> Сервисы</a></li>
                    <li><a id="change-staff" href="{% url 'settings:personal-settings' enterprise.pk %}"><span class="fa fa-group"></span> Персонал</a></li>
                </ul>
            </li>
            <li>
            {% else %}
                <li>
                    <a href="{% url 'enterprise:create' user.pk %}"><i class="fa fa-newspaper-o"></i><span class="nav-label">{% trans 'Include enterprise' %}</span></a>
                </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i><span class="nav-label">{% trans 'Exit' %}</span></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/snippets/script.html
{% load static %}

<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<!-- JQuery cookie -->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

<!-- Flot -->
<script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.spline.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>

<!-- Peity -->
<script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'js/demo/peity-demo.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

<!-- jQuery UI -->
<script src="{% static 'js/plugins/jquery-ui/jquery-ui.min.js' %}"></script>

<!-- GITTER -->
<script src="{% static 'js/plugins/gritter/jquery.gritter.min.js' %}"></script>

<!-- Sparkline -->
<script src="{% static 'js/plugins/sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Sparkline demo data  -->
<script src="{% static 'js/demo/sparkline-demo.js' %}"></script>

<!-- ChartJS-->
<script src="{% static 'js/plugins/chartJs/Chart.min.js' %}"></script>

<!-- Toastr -->
<script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>

<!-- Mask -->
<script src="{% static 'js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>

<!-- Monent -->
<script src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>

<!-- Fullcalendar -->
<script src="{% static 'js/plugins/fullcalendar/fullcalendar.min.js' %}"></script>

<!-- MultiCalendar -->
<script src="{% static 'js/jquery-ui.multidatespicker.js' %}"></script>

<!-- Scripts -->
<script src="{% static 'js/calender-initial.js' %}"></script>

<!-- SUMMERNOTE -->
<script src="{% static 'js/plugins/summernote/summernote.min.js' %}"></script>

<!-- FooTable -->
<script src="{% static 'js/plugins/footable/footable.all.min.js' %}"></script>

<!-- Dual Listbox -->
<script src="{% static 'js/plugins/dualListbox/jquery.bootstrap-duallistbox.js' %}"></script>

<!-- Rater -->
<script src="{% static 'js/rater.js' %}"></script>

<!-- Timetable -->
<script src="{% static 'js/timetable.min.js' %}"></script>

<!-- Skeduler -->
<script src="{% static 'js/jquery.skeduler.js' %}"></script>

<!-- Chosen -->
<script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>

<!-- React -->
<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

<!-- Babel -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js"></script>

<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<script>
    $('textarea').summernote();
</script>

templates/snippets/style.html
{% load static %}

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

<!-- Toastr style -->
<link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<!-- FooTable -->
<link href="{% static 'css/plugins/footable/footable.core.css' %}" rel="stylesheet">

<!-- Gritter -->
<link href="{% static 'js/plugins/gritter/jquery.gritter.css' %}" rel="stylesheet">

<!-- JQ calender ui -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">

<!-- Multi calendar css -->
<link rel="stylesheet" href="{% static 'css/jquery-ui.multidatespicker.css' %}">

<!-- Timetable -->
<link rel="stylesheet" href="{% static 'css/timetablejs.css' %}">

<!-- Skeduler -->
<link rel="stylesheet" href="{% static 'css/jquery.skeduler.css' %}">

<!-- Chosen -->
<link rel="stylesheet" href="{% static 'css/plugins/chosen/bootstrap-chosen.css' %}">

<!-- Full Calendar -->
<link rel="stylesheet" href="{% static 'css/plugins/fullcalendar/fullcalendar.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/fullcalendar/fullcalendar.print.css' %}" media="print">

<!-- Summernote -->

<link href="{% static 'css/plugins/summernote/summernote.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/summernote/summernote-bs3.css' %}" rel="stylesheet">

<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<!-- Dueal select -->
<link href="{% static 'css/plugins/dualListbox/bootstrap-duallistbox.min.css' %}" rel="stylesheet">