api/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # Stable
    url(r'', include('api.v1.urls')),
    # Version
    url(r'^v1/', include('api.v1.urls')),
]

api/v1/enterprise/urls.py
from django.conf.urls import url

from .views import (
    EnterpriseAPIListView,
    EnterpriseAPIUserView,
    EnterpriseAPIDetailView,
    CategoryOfServicesAPIListView,
    CategoryOfServiceAPIDetailView,
CityListView
)

urlpatterns = [
    url(r'^$', EnterpriseAPIListView.as_view(), name='list'),
    url(r'^(?P<id>\d+)/$', EnterpriseAPIUserView.as_view(), name='list-profile'),
    url(r'^detail/(?P<id>\d+)/', EnterpriseAPIDetailView.as_view(), name='detail'),
    url(r'^(?P<id>\d+)/service/$', CategoryOfServicesAPIListView.as_view(), name='services'),
    url(r'^service/(?P<id>\d+)/detail/$', CategoryOfServiceAPIDetailView.as_view(), name='service-detail'),
    url(r'^city/$', CityListView.as_view(), name='city')
]

employee/urls.py
from django.conf.urls import url

from .views import (
    employee,
    new_employee
)

urlpatterns = [
    url(r'^$', employee, name='employee'),
    url(r'^new$', new_employee, name='new-employee'),
]

enterprise/urls.py
from django.conf.urls import url

from .views import (
    dashboard,
    create,
    detail,
    update
)

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    # OLD
    url(r'^enterprise/create/(?P<pk>[\w-]+)/$', create, name='create'),
    url(r'^enterprise/detail/(?P<pk>[\w-]+)/$', detail, name="detail"),
    url(r'^enterprise/update/(?P<pk>[\w-]+)/$', update, name="update"),
]

reservator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = i18n_patterns(
    # apps urls
    # flatpages
    url(r'^$', include('django.contrib.flatpages.urls')),
    # admin dashboard
    url(r'^dashboard/', include('enterprise.urls', namespace='enterprise')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^service/', include('service.urls', namespace='service')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    # auth
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # Social
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^api/enterprise/', include('enterprise.api.urls', namespace='api-enterprise')),
    # url(r'^api/employee/', include('employee.api.urls', namespace='api-employee')),
    # url(r'^api/profile/', include('account.api.profile.urls', namespace='api-profile')),
    # url(r'^api/auth/', include('account.api.urls', namespace='api-auth')),
    # Languages
    url(r'^lang/(?P<lang_code>[a-z]{2})/$', views.lang, name='lang'),
    # Ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # admin
    url(r'^area51/', admin.site.urls),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

enterprise/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
from django.conf import settings
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
import datetime

from phonenumber_field.modelfields import PhoneNumberField
from multiselectfield import MultiSelectField
from geoposition.fields import GeopositionField

from jsonfield import JSONField  # Only develop

User = settings.AUTH_USER_MODEL


# Upload path
def upload_enterprise_image(instance, filename):
    return "enterprise/{title}/{filename}".format(title=instance.title, filename=filename)


########### QuerySet ##################
class EnterpriseQuerySet(models.QuerySet):
    def search(self, query):
        if query:
            return self.filter(
                Q(name__icontains=query) |
                Q(employee__sex__iexact=query) |
                Q(employee__sex__icontains=query)
            ).distinct()
        return self
    pass


########### MANAGERS ##################
class EnterpriseManager(models.Manager):
    def get_queryset(self):
        return EnterpriseQuerySet(self.model, using=self._db)

    def get_employee(self, enterprise):
        from employee.models import Employee
        return Employee.objects.filter(enterprise=enterprise).filter(fired=False)

        # def search(self, query):
        #     return self.get_queryset().search(query)


########### Models ###############
class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('City')
        verbose_name_plural = _('Cities')
        ordering = ('-name',)


class Enterprise(models.Model):
    owner = models.OneToOneField(User, help_text=_('Owner field'),
                                 verbose_name=_('Owner'))
    title = models.CharField(max_length=255, help_text=_('Name enterprise'),
                             verbose_name=_('Title'))
    logo = models.ImageField(upload_to=upload_enterprise_image,
                             help_text='Logo image', blank=True,
                             verbose_name=_('Logo'))
    category = models.CharField(max_length=200, blank=True, null=True,
                                help_text='Category', verbose_name=_('Category'))
    description = models.TextField(help_text=_('Short descriptions'),
                                   blank=True, verbose_name=_('Description'))
    schedule = JSONField(blank=True, null=True,
                         help_text=_('Schedule enterprise'),
                         verbose_name=_('Schedule'))
    city = models.ForeignKey(City, help_text=_('Select city'),
                             verbose_name=_('City'), blank=True, null=True)
    address = models.CharField(max_length=255, help_text=_('Address enterprise'),
                               null=True, blank=True, verbose_name=_('Address'))
    phone = PhoneNumberField(max_length=255, help_text=_('Contact phone'),
                             blank=True, verbose_name=_('Phone'))
    index = models.IntegerField(help_text=_('Index'), verbose_name=_('Index'),
                                blank=True, default=0)
    site = models.URLField(help_text='www.example.com',
                           blank=True, verbose_name=_('Site'))
    active = models.BooleanField(default=True, help_text=_('Is active'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = EnterpriseManager()

    class Meta:
        db_table = 'db_enterprise'
        verbose_name = _('Enterprise')
        verbose_name_plural = _('Enterprises')
        ordering = ['-pk']

    def __str__(self):
        return str(self.title)[:50]

    def get_absolute_url(self):
        return reverse("enterprise:detail", kwargs={'pk': self.pk})

    def get_services(self):
        from service.models import Service
        return Service.objects.filter(enterprise__owner=self.pk)

    def get_employee(self):
        id = self.id
        return Enterprise.objects.get_employee(id)

# @receiver(post_save, sender=User)
# def create_enterprise(sender, instance, created, **kwargs):
#     if created:
#         Enterprise.objects.get_or_create(owner=instance)

enterprise/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget

from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from .models import Enterprise, City


class EnterpriseCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Название')
    category = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='Категория')
    phone = forms.CharField(widget=PhoneNumberInternationalFallbackWidget(attrs={
        'class': 'form-control',
        'data-mask': '+38 (999) 999-99-99'
    }), label="Контактный телефон")
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                              label="Адрес")
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'summernote'}),
                                  label='Описание')
    city = forms.ModelChoiceField(City.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}),
                                  label="Город")

    class Meta:
        model = Enterprise
        exclude = ('owner', 'active_stuff_count', 'group_priority', 'schedule', 'logo', 'active', )


class EnterpriseUpdateScheduleForm(forms.ModelForm):
    class Meta:
        model = Enterprise
        fields = ('schedule',)


class EnterpriseUpdateForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Название')
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'summernote'}),
                                  label='Описание')

    # def __init__(self, *args, **kwargs):
    #     super(EnterpriseUpdateForm, self).__init__(*args, **kwargs)
    #     self.fields['city'].queryset = City.objects.all()


class EnterpriseUpdateContactForm(forms.Form):
    city = forms.ModelChoiceField(City.objects.all(),
                                  widget=forms.Select(attrs={'class': 'form-control'}),
                                  label="Город")
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                              label="Адрес")
    phone = forms.CharField(widget=PhoneNumberInternationalFallbackWidget(attrs={
        'class': 'form-control',
        'data-mask': '+38 (999) 999-99-99'
    }), label="Контактный телефон")


class EnterpriseUpdateLogoForm(forms.Form):
    logo = forms.ImageField()

api/v1/enterprise/views.py
from rest_framework import generics, mixins, permissions

from .serializer import EnterpriseSerializer, CategoryOfServicesSerializers, CitySerializer
from .permissions import IsOwner
from enterprise.models import Enterprise, City
from service.models import Service


class EnterpriseAPIListView(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    # passed_id = 'id'
    search_fields = ('title', 'description',)
    serializer_class = EnterpriseSerializer
    queryset = Enterprise.objects.all()


class EnterpriseAPIUserView(mixins.UpdateModelMixin, mixins.CreateModelMixin, generics.ListAPIView):
    permissions_class = [permissions.IsAdminUser]
    serializer_class = EnterpriseSerializer

    def get_queryset(self):
        return Enterprise.objects.filter()

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class EnterpriseAPIDetailView(mixins.UpdateModelMixin, generics.RetrieveAPIView):
    permission_classes = [IsOwner]
    serializer_class = EnterpriseSerializer
    lookup_field = 'id'
    queryset = Enterprise.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def perform_update(self, serializer):
        serializer.save(owner=self.request.user)


class CategoryOfServicesAPIListView(mixins.UpdateModelMixin, generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = CategoryOfServicesSerializers

    # lookup_field = 'id'

    def get_queryset(self):
        return Service.objects.filter(enterprise=self.kwargs['id'])

    def post(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(enterprise=self.kwargs['enterprise'])


class CategoryOfServiceAPIDetailView(mixins.UpdateModelMixin, mixins.DestroyModelMixin, generics.RetrieveAPIView):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = CategoryOfServicesSerializers
    lookup_field = 'id'
    queryset = Service.objects.all()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class CityListView(generics.ListAPIView):
    serializer_class = CitySerializer
    queryset = City.objects.all()

enterprise/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.forms.models import model_to_dict
from django.views.generic import FormView
from reservator.decorators import manager_required
from .models import Enterprise
from .forms import EnterpriseCreateForm, EnterpriseUpdateForm
from service.models import Category, Service
from employee.models import Employee
from profile.models import ClientProfile
from django.contrib.auth.decorators import permission_required


# Create your views here.


@login_required
def dashboard(request):
    template_name = 'enterprise/dashboard.html'
    template_data = {}
    return render(request, template_name, template_data)


def create(request, pk):
    form = EnterpriseCreateForm(request.POST or None, request.FILES or None)
    template_data = {'form': form}
    return render(request, 'enterprise/enterprise_create.html', template_data)


@manager_required
def detail(request, pk):
    instance = Enterprise.objects.get(pk=pk)
    category = Category.objects.filter(enterprise=instance)
    service = Service.objects.filter(service__enterprise=instance)
    employees = Employee.objects.filter(enterprise=pk)
    template_name = 'enterprise/enterprise_detail.html'
    template_data = {
        'instance': instance,
        'category': category,
        'service': service,
        'employees': employees
    }
    return render(request, template_name, template_data)


@manager_required
def update(request, pk):
    instance = Enterprise.objects.get(pk=pk)

    if request.POST:
        form = EnterpriseUpdateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            update_data = form.cleaned_data
            Enterprise.objects.filter(pk=instance.id).update(**update_data)
            return HttpResponseRedirect('/')
    else:
        form = EnterpriseUpdateForm(initial=model_to_dict(instance))
    template_name = 'enterprise/enterprise_update.html'
    template_data = {'instance': instance, 'form': form}
    return render(request, template_name, template_data)

enterprise/templates/enterprise/dashboard.html
{% extends 'base_index.html' %}
{% load i18n %}
{% load get_current_language from i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}
    Dashboard {{ enterprise.title }} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper">
                <h1>Dashboard!</h1>
                <a href="{% url 'lang' 'ru' %}">{% trans "Русский" %}</a>
                <a href="{% url 'lang' 'uk' %}">{% trans "Українська" %}</a>
                <a href="{% url 'lang' 'en' %}">{% trans "Английский" %}</a>
                {{ enterprise }}
            </div>
        </div>
    </div>
{% endblock %}

enterprise/templates/enterprise/enterprise_create.html
{% extends 'base_index.html' %}

{% block content %}
    {{ form.as_p }}
{% endblock %}

enterprise/templates/enterprise/enterprise_update.html
{% extends "base_index.html" %}

{% block title %}
	Update | {{ block.super }}
{% endblock %}

{% block content %}
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактировать</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index-2.html">Главная</a>
                </li>
                <li>
                    <a>Компания</a>
                </li>
                <li class="active">
                    <strong>Редактировать</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight ecommerce">

        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1"> Основное</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
<!--
                                    <fieldset class="form-horizontal">
                                        <div class="form-group"><label class="col-sm-2 control-label">Name:</label>
                                            <div class="col-sm-10"><input id="id_title" type="text" class="form-control" placeholder="Enterprise"></div>
                                        </div>
                                        <div class="form-group"><label class="col-sm-2 control-label">Описание компании:</label>
                                            <div class="col-sm-10">
                                                <div class="summernote" id="id_short_descr">
                                                    

                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group"><label class="col-sm-2 control-label">Город:</label>
                                            <div class="col-sm-10">
                                            	<select id="id_city" type="text" class="form-control" placeholder="Kiev">
                                            		<option value="">------------------</option>
                                            	</select>
                                            </div>
                                        </div>
                                        <div class="form-group"><label class="col-sm-2 control-label">Адрес:</label>
                                            <div class="col-sm-10"><input id="id_address" type="text" class="form-control" placeholder="Sheets containing Lorem"></div>
                                        </div>
                                        <div class="form-group"><label class="col-sm-2 control-label">Телефон:</label>
                                            <div class="col-sm-10"><input id="id_phone" type="text" class="form-control" placeholder="Lorem, Ipsum, has, been"></div>
                                        </div>
                                        <div class="form-group">
                                        	<div class="col-sm-2 col-sm-offset-2">
	                                    		<button id="submit" class="btn btn-success">
	                                        		OK!
		                                        </button>
                                        	</div>
                                        	
	                                    </div>
                                    </fieldset>
-->
									<form class="form-horizontal" method="POST" action="">
										{% csrf_token %}
										{% for field in form %}
											<div class="form-group">
												<label class="col-sm-2 control-label" for="">
													{{ field.label_tag }}
												</label>
												<div class="col-sm-10">
													{{ field }}
												</div>
											</div>
										{% endfor %}
										<div class="form-group">
											<div class="col-sm-2 col-sm-offset-2">
												<button class="btn btn-success btn-block">Сохранить!</button>
											</div>
										</div>
									</form>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
	<script>
		$(document).ready(function(){
			$(".summernote").summernote();
		});
	</script>
{% endblock %}

enterprise/templates/enterprise/include_employee.html
{% extends "base_index.html" %}

{% block title %}
  Add Employee | {{ block.super }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 align='center'>Registration employee form</h1>
        <form action="." method="post" align='center'>
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-success btn-block">Create</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block custom_script %}
<script>
  $(document).ready(function(){
    $('p').addClass('form-group row');
    $('label').addClass('label-control col-2')
    $('input').addClass('form-control col-10');
    $('textarea').addClass('form-control col-10');
    $('select').addClass('form-control col-10');
    $('.timepicker').timepicker({'timeFormat': 'H:mm:ss' });
    $('#id_works').addClass('list-inline form-group');
		$('#id_works li').addClass('list-inline-item');
    $('input[type=checkbox]').removeClass('form-control col-10');
  })
</script>
{% endblock %}